{
  "$comment": "Generated by /founding-prompt. Single source of truth for this project's real test/build commands and key document locations. bin/verify-gate.sh reads testCommand from here if present, falling back to npm-only detection (package.json's scripts.test) when this file is absent or testCommand is unset -- so projects that don't use npm (Python, Go, Rust, etc.) get a working Stop-hook test gate too, not just an allow-everything no-op.",
  "testCommand": "npm test",
  "buildCommand": "npm run build",
  "keyFiles": {
    "prd": "PRD.md",
    "agents": "AGENTS.md",
    "changelog": "CHANGELOG.md"
  }
}
