# {{PRODUCT_NAME}} — Product Requirements

> {{ONE_SENTENCE_PROBLEM_STATEMENT}}
> e.g. "Small business owners can't efficiently manage employee schedules."

<!--
  No canonical PRD format exists for AI-agent consumption (verified via research,
  July 2026) — the pattern below is synthesized from the convergent shape found
  across vibe-coding template repos: explicit behavior rules over feature prose,
  and an explicit non-goals list. Generated by the /founding-prompt skill.
-->

## Who this is for

**Target users:** {{TARGET_USERS}}
<!-- e.g. "Business owners and their employees at companies with 5-50 hourly workers." -->

**The job they're hiring this product to do:** {{JTBD_STATEMENT}}

## Core features (max 5 for v1 — resist adding more)

1. {{FEATURE_1}}
2. {{FEATURE_2}}
3. {{FEATURE_3}}
4. {{FEATURE_4}}
5. {{FEATURE_5}}

## Behavior rules

State exact behavior, not vague feature descriptions. Every rule an agent
implements should trace back to one of these.

- WHEN {{trigger}} THEN {{system response}}
- WHEN {{trigger}} THEN {{system response}}
- WHEN {{trigger}} THEN {{system response}}

## Data model

{{DATA_MODEL}}
<!-- e.g.
- Users: name, email, plan type
- Schedules: employee_id, shift_start, shift_end, status
- Payments: subscription status, billing history
-->

## Integrations

{{INTEGRATIONS}}
<!-- e.g. Supabase (db/auth), Stripe (payments), Vercel (hosting) -->

## Success metrics

{{SUCCESS_METRICS}}
<!-- e.g. "An owner can create next week's schedule in under 5 minutes." -->

## Explicitly NOT building in this version

- {{NON_GOAL_1}}
- {{NON_GOAL_2}}

This list exists so the agent (and you) can say no to scope creep without
re-litigating it every time.

## Status

- [ ] {{FEATURE_1}}
- [ ] {{FEATURE_2}}
- [ ] {{FEATURE_3}}
- [ ] {{FEATURE_4}}
- [ ] {{FEATURE_5}}
